# Exploratory Data Analysis

## Dataset Information
This online retail transaction dataset was extracted from the UC Irvine Machine Learning Repository. It contains all the **541909 transactions** occuring for a UK-based and registered, non-store online retail between 01/12/2009 and 09/12/2011. The company mainly seels unique all-occasion gift-ware. Many customers of the company are wholesalers


### Dataset Structure

Each row represents an invoice item, with their corresponding:

    - InvoiceNo
    - StockCode
    - Description
    - Quantity
    - InvoiceData
    - UnitPrice
    - CustomerID
    - Country

In [1]:
import pandas as pd

file_add = "../data/raw/Online_Retail.xlsx"
df_retail = pd.read_excel(file_add, sheet_name="Online Retail") 

df_retail

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

### Data Anomalies

**InvoiceNo**

Represents the unique identifier for each invoice. 
For each invoices, you can have multiple items. That's why you can see duplicate InvoiceNo.

No missing values.

In [32]:
df_retail.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

**StockCode**

Represents the unique identifier of the product.

There are special stock codes that do not represent actual physical prodcuts. They represent operational transcations:

Some Examples:

    - DOT
    - POST
    - BANK CHARGES
    - M
    - D
    - C2
    - CRUK

**Description**

This contains a short description of the product.

**CustomerID**

Approximately 25% of total transactions **(or 135080 transactions)** have a missing `CustomerID`

In [2]:
df_retail.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
536981,581234,72817,NaN,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
538504,581406,46000M,POLYESTER FILLER PAD 45x45cm,240,2011-12-08 13:58:00,0.0,NaN,United Kingdom
538505,581406,46000S,POLYESTER FILLER PAD 40x40cm,300,2011-12-08 13:58:00,0.0,NaN,United Kingdom
538554,581408,85175,NaN,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom
538919,581422,23169,smashed,-235,2011-12-08 15:24:00,0.0,NaN,United Kingdom

array([False])

**UnitPrice**

There are no missing values for `UnitPrice`, but there are **2515 entries** with 0.00 UnitPrice values which is an anomaly(what products costs 0 each unit?). 
Maybe these are promotional gifts, buy-one-get-one free items, samples, replacements, internal inventory transfers, etc.. 

*No action taken until we gather more information.*

In [31]:
df_retail[df_retail["UnitPrice"]==0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
536981,581234,72817,NaN,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
538504,581406,46000M,POLYESTER FILLER PAD 45x45cm,240,2011-12-08 13:58:00,0.0,NaN,United Kingdom
538505,581406,46000S,POLYESTER FILLER PAD 40x40cm,300,2011-12-08 13:58:00,0.0,NaN,United Kingdom
538554,581408,85175,NaN,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom
538919,581422,23169,smashed,-235,2011-12-08 15:24:00,0.0,NaN,United Kingdom


Also, 2475 entries out of the total 2515 entries with 0 `UnitPrice` have **missing `CustomerID`**.

In [30]:
len_zero_unitprice = len(df_retail[df_retail['UnitPrice'] == 0 ])
len_customer_id_null = len(df_retail[(df_retail['CustomerID'].isnull()) & (df_retail['UnitPrice'] == 0 )])

print(f"Number of rows with zero UnitPrice: {len_zero_unitprice}")
print(f"{len_customer_id_null/len_zero_unitprice*100:.2f}% of rows with zero UnitPrice have null CustomerID")

Number of rows with zero UnitPrice: 2515
98.41% of rows with zero UnitPrice have null CustomerID

In [33]:

df_invoices = (
    df_retail.groupby("InvoiceNo", as_index=False)
    .agg({
        "InvoiceDate" : "min",
        "CustomerID" : "first",
        "Country" : "first"
    })
)

df_invoices = df_invoices.rename(columns={
    "InvoiceNo" : "invoice_no",
    "InvoiceDate" : "invoice_date",
    "CustomerID" : "customer_id",
    "Country" : "country"
})


df_invoiceitems = (
    df_retail[
        ["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice"]
    ]
).copy()

df_invoiceitems = df_invoiceitems.rename(columns={
    "InvoiceNo" : "invoice_no",
    "StockCode" : "stock_code",
    "Description" : "description",
    "Quantity" : "quantity",
    "UnitPrice" : "unit_price"
})

In [34]:
df_invoices['invoice_no'].value_counts().value_counts()

count
1    25900
Name: count, dtype: int64

In [30]:
df_retail[df_retail['InvoiceNo'] == 536591]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2421,536591,21427,SKULLS STORAGE BOX SMALL,1,2010-12-01 16:57:00,2.10,14606.0,United Kingdom
2422,536591,22135,LADLE LOVE HEART PINK,1,2010-12-01 16:57:00,0.42,14606.0,United Kingdom
2423,536591,90214M,"LETTER ""M"" BLING KEY RING",1,2010-12-01 16:57:00,1.25,14606.0,United Kingdom
2424,536591,90214V,"LETTER ""V"" BLING KEY RING",1,2010-12-01 16:57:00,1.25,14606.0,United Kingdom
2425,536591,90214S,"LETTER ""S"" BLING KEY RING",1,2010-12-01 16:57:00,1.25,14606.0,United Kingdom
2426,536591,90214J,"LETTER ""J"" BLING KEY RING",2,2010-12-01 16:57:00,1.25,14606.0,United Kingdom
2427,536591,22386,JUMBO BAG PINK POLKADOT,1,2010-12-01 16:57:00,1.95,14606.0,United Kingdom
2428,536591,22378,WALL TIDY RETROSPOT,1,2010-12-01 16:57:00,2.10,14606.0,United Kingdom
2429,536591,20750,RED RETROSPOT MINI CASES,1,2010-12-01 16:57:00,7.95,14606.0,United Kingdom
2430,536591,21888,BINGO SET,1,2010-12-01 16:57:00,3.75,14606.0,United Kingdom
2431,536591,22321,BIRD DECORATION RED RETROSPOT,1,2010-12-01 16:57:00,0.85,14606.0,United Kingdom
2432,536591,21789,KIDS RAIN MAC PINK,1,2010-12-01 16:57:00,0.85,14606.0,United Kingdom
2433,536591,21238,RED RETROSPOT CUP,1,2010-12-01 16:57:00,0.85,14606.0,United Kingdom
2434,536591,21629,SQUARE FLOOR CUSHION VINTAGE RED,1,2010-12-01 16:57:00,7.95,14606.0,United Kingdom
2435,536591,22379,RECYCLING BAG RETROSPOT,1,2010-12-01 16:57:00,2.10,14606.0,United Kingdom
2436,536591,72807C,SET/3 VANILLA SCENTED CANDLE IN BOX,2,2010-12-01 16:57:00,4.25,14606.0,United Kingdom
2437,536591,22497,SET OF 2 TINS VINTAGE BATHROOM,1,2010-12-01 16:57:00,4.25,14606.0,United Kingdom
2438,536591,21850,BLUE DIAMANTE PEN IN GIFT BOX,1,2010-12-01 16:57:00,4.95,14606.0,United Kingdom
2439,536591,20978,36 PENCILS TUBE SKULLS,2,2010-12-01 16:57:00,1.25,14606.0,United Kingdom
2440,536591,20768,GREEN FERN JOURNAL,1,2010-12-01 16:57:00,2.55,14606.0,United Kingdom
2441,536591,22081,RIBBON REEL FLORA + FAUNA,1,2010-12-01 16:57:00,1.65,14606.0,United Kingdom
2442,536591,20780,BLACK EAR MUFF HEADPHONES,1,2010-12-01 16:57:00,5.49,14606.0,United Kingdom
2443,536591,51014C,"FEATHER PEN,COAL BLACK",12,2010-12-01 16:57:00,0.85,14606.0,United Kingdom
2444,536591,21398,RED POLKADOT COFFEE MUG,1,2010-12-01 16:57:00,2.10,14606.0,United Kingdom
2445,536591,22476,EMPIRE UNION JACK TV DINNER TRAY,2,2010-12-01 16:57:00,4.95,14606.0,United Kingdom
2446,536591,21643,ASSORTED TUTTI FRUTTI MIRROR,3,2010-12-01 16:57:00,1.25,14606.0,United Kingdom
2447,536591,72741,GRAND CHOCOLATECANDLE,27,2010-12-01 16:57:00,1.45,14606.0,United Kingdom
2448,536591,21620,SET OF 4 ROSE BOTANICAL CANDLES,1,2010-12-01 16:57:00,3.75,14606.0,United Kingdom
2449,536591,37449,CERAMIC CAKE STAND + HANGING CAKES,1,2010-12-01 16:57:00,9.95,14606.0,United Kingdom
2450,536591,22260,FELT EGG COSY BLUE RABBIT,5,2010-12-01 16:57:00,0.85,14606.0,United Kingdom
2451,536591,22136,LOVE HEART SOCK HANGER,1,2010-12-01 16:57:00,1.65,14606.0,United Kingdom
2452,536591,47591B,SCOTTIES CHILDRENS APRON,1,2010-12-01 16:57:00,1.65,14606.0,United Kingdom
2453,536591,21041,RED RETROSPOT OVEN GLOVE DOUBLE,1,2010-12-01 16:57:00,2.95,14606.0,United Kingdom
2454,536591,21035,SET/2 RED RETROSPOT TEA TOWELS,1,2010-12-01 16:57:00,2.95,14606.0,United Kingdom
2455,536591,85064,CREAM SWEETHEART LETTER RACK,2,2010-12-01 16:58:00,5.45,14606.0,United Kingdom
2456,536591,22121,NOEL WOODEN BLOCK LETTERS,2,2010-12-01 16:58:00,5.95,14606.0,United Kingdom
2457,536591,21488,RED WHITE SCARF HOT WATER BOTTLE,1,2010-12-01 16:58:00,3.95,14606.0,United Kingdom
2458,536591,21484,CHICK GREY HOT WATER BOTTLE,2,2010-12-01 16:58:00,3.45,14606.0,United Kingdom
2459,536591,22357,KINGS CHOICE BISCUIT TIN,1,2010-12-01 16:58:00,4.25,14606.0,United Kingdom
2460,536591,21985,PACK OF 12 HEARTS DESIGN TISSUES,4,2010-12-01 16:58:00,0.29,14606.0,United Kingdom

In [ ]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg://postgres:Patriotism0102@localhost:5432/retail_sales"
)

df_invoiceitems.to_sql(
    "invoiceitems",
    engine,
    if_exists = "append",
    index=False
)

-1

:

In [50]:
df_retail[df_retail["CustomerID"] == 12394]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
177881,552188,22629,SPACEBOY LUNCH BOX,12,2011-05-06 14:01:00,1.95,12394.0,Belgium,23.40
177882,552188,22551,PLASTERS IN TIN SPACEBOY,12,2011-05-06 14:01:00,1.65,12394.0,Belgium,19.80
177883,552188,22630,DOLLY GIRL LUNCH BOX,12,2011-05-06 14:01:00,1.95,12394.0,Belgium,23.40
177884,552188,22557,PLASTERS IN TIN VINTAGE PAISLEY,12,2011-05-06 14:01:00,1.65,12394.0,Belgium,19.80
177885,552188,21240,BLUE POLKADOT CUP,8,2011-05-06 14:01:00,0.85,12394.0,Belgium,6.80
177886,552188,20675,BLUE POLKADOT BOWL,8,2011-05-06 14:01:00,1.25,12394.0,Belgium,10.00
177887,552188,20674,GREEN POLKADOT BOWL,8,2011-05-06 14:01:00,1.25,12394.0,Belgium,10.00
177888,552188,20676,RED RETROSPOT BOWL,8,2011-05-06 14:01:00,1.25,12394.0,Belgium,10.00
177889,552188,21245,GREEN POLKADOT PLATE,8,2011-05-06 14:01:00,1.69,12394.0,Belgium,13.52
177890,552188,21244,BLUE POLKADOT PLATE,8,2011-05-06 14:01:00,1.69,12394.0,Belgium,13.52
177891,552188,21242,RED RETROSPOT PLATE,16,2011-05-06 14:01:00,1.69,12394.0,Belgium,27.04
177892,552188,23256,CHILDRENS CUTLERY SPACEBOY,8,2011-05-06 14:01:00,4.15,12394.0,Belgium,33.20
177893,552188,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-05-06 14:01:00,4.15,12394.0,Belgium,16.60
177894,552188,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-05-06 14:01:00,4.15,12394.0,Belgium,16.60
177895,552188,21238,RED RETROSPOT CUP,8,2011-05-06 14:01:00,0.85,12394.0,Belgium,6.80
177896,552188,22631,CIRCUS PARADE LUNCH BOX,12,2011-05-06 14:01:00,1.95,12394.0,Belgium,23.40
177897,552188,22556,PLASTERS IN TIN CIRCUS PARADE,12,2011-05-06 14:01:00,1.65,12394.0,Belgium,19.80
177898,552188,22634,CHILDS BREAKFAST SET SPACEBOY,2,2011-05-06 14:01:00,9.95,12394.0,Belgium,19.90
177899,552188,21452,TOADSTOOL MONEY BOX,6,2011-05-06 14:01:00,2.95,12394.0,Belgium,17.70
177900,552188,22555,PLASTERS IN TIN STRONGMAN,12,2011-05-06 14:01:00,1.65,12394.0,Belgium,19.80
177901,552188,POST,POSTAGE,2,2011-05-06 14:01:00,15.00,12394.0,Belgium,30.00
383089,569997,23245,SET OF 3 REGENCY CAKE TINS,32,2011-10-07 08:08:00,4.15,12394.0,Denmark,132.80
383090,569997,23295,SET OF 12 MINI LOAF BAKING CASES,256,2011-10-07 08:08:00,0.72,12394.0,Denmark,184.32
383091,569997,23296,SET OF 6 TEA TIME BAKING CASES,256,2011-10-07 08:08:00,1.04,12394.0,Denmark,266.24
383092,569997,23293,SET OF 12 FAIRY CAKE BAKING CASES,48,2011-10-07 08:08:00,0.83,12394.0,Denmark,39.84
383093,569997,37495,FAIRY CAKE BIRTHDAY CANDLE SET,36,2011-10-07 08:08:00,2.95,12394.0,Denmark,106.20
383094,569997,POST,POSTAGE,9,2011-10-07 08:08:00,18.00,12394.0,Denmark,162.00

In [47]:
print("Number of Customers:", df_retail['CustomerID'].nunique())

customer_products = (df_retail.groupby(["CustomerID", "StockCode"])
 .agg(
     Quantity = ("Quantity", "sum"),
     Revenue = ("Revenue", "sum")
 ))

customer_products.groupby(level=0)["Quantity"].idxmax()

Number of Customers: 4372

CustomerID
12346.0     (12346.0, 23166)
12347.0     (12347.0, 23076)
12348.0     (12348.0, 23077)
12349.0     (12349.0, 21231)
12350.0     (12350.0, 22348)
                 ...
18280.0     (18280.0, 22084)
18281.0     (18281.0, 22028)
18282.0     (18282.0, 23187)
18283.0     (18283.0, 22418)
18287.0    (18287.0, 85039B)
Name: Quantity, Length: 4372, dtype: object

In [9]:
df_retail.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [10]:
df_retail.nunique()

InvoiceNo      25900
StockCode       4070
Description     4223
Quantity         722
InvoiceDate    23260
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64

In [48]:
df_retail.duplicated().sum()

np.int64(5268)

In [60]:
df_retail['Country'].value_counts()

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [65]:
n_cancelled = df_retail[df_retail["InvoiceNo"].str.startswith("C", na=False)].shape[0]
n_duplicate = df_retail[df_retail["Quantity"] < 0].shape[0]
n_neg_quan = df_retail[df_retail["Quantity"] < 0].shape[0]
n_neg_price = df_retail[df_retail["UnitPrice"] <= 0].shape[0]



print(f"Number of cancelled orders: {n_cancelled}")
print(f"Number of duplicate orders: {n_duplicate}")
print(f"Number of negative quantities: {n_neg_quan}")
print(f"Number of non-positive prices: {n_neg_price}")

Number of cancelled orders: 9288
Number of duplicate orders: 10624
Number of negative quantities: 10624
Number of non-positive prices: 2517

In [68]:
duplicates = df_retail[df_retail.duplicated(keep=False)]

duplicates.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom,4.95
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom,2.10
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom,1.25
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom,1.25
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom,2.95
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom,2.10
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom,2.95
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom,4.95
548,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom,2.95
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom,2.95

In [118]:
DOT_stock_code = df_retail[(df_retail["StockCode"] == "BANK CHARGES") &(df_retail["Quantity"] < 0)]

DOT_stock_code

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
14435,C537572,BANK CHARGES,Bank Charges,-1,2010-12-07 12:00:00,95.38,NaN,United Kingdom,-95.38
28992,C538680,BANK CHARGES,Bank Charges,-1,2010-12-13 17:10:00,966.92,NaN,United Kingdom,-966.92
64573,C541653,BANK CHARGES,Bank Charges,-1,2011-01-20 11:50:00,1050.15,NaN,United Kingdom,-1050.15
90558,C544049,BANK CHARGES,Bank Charges,-1,2011-02-15 12:39:00,566.37,NaN,United Kingdom,-566.37
96675,C544575,BANK CHARGES,Bank Charges,-1,2011-02-21 13:58:00,134.76,NaN,United Kingdom,-134.76
96676,C544576,BANK CHARGES,Bank Charges,-1,2011-02-21 14:01:00,149.16,NaN,United Kingdom,-149.16
96715,C544584,BANK CHARGES,Bank Charges,-1,2011-02-21 14:52:00,109.84,NaN,United Kingdom,-109.84
112233,C545887,BANK CHARGES,Bank Charges,-1,2011-03-07 15:54:00,326.68,NaN,United Kingdom,-326.68
124025,C546943,BANK CHARGES,Bank Charges,-1,2011-03-18 11:11:00,56.93,NaN,United Kingdom,-56.93
166515,C550932,BANK CHARGES,Bank Charges,-1,2011-04-21 15:12:00,475.69,NaN,United Kingdom,-475.69
181258,C552458,BANK CHARGES,Bank Charges,-1,2011-05-09 14:41:00,440.29,NaN,United Kingdom,-440.29
193136,C553511,BANK CHARGES,Bank Charges,-1,2011-05-17 13:49:00,86.90,NaN,United Kingdom,-86.90
193444,C553528,BANK CHARGES,Bank Charges,-1,2011-05-17 14:58:00,82.73,NaN,United Kingdom,-82.73
227400,C556874,BANK CHARGES,Bank Charges,-1,2011-06-15 11:49:00,464.52,NaN,United Kingdom,-464.52
242465,C558349,BANK CHARGES,Bank Charges,-1,2011-06-28 14:50:00,82.89,NaN,United Kingdom,-82.89
273311,C560823,BANK CHARGES,Bank Charges,-1,2011-07-21 11:22:00,21.90,NaN,United Kingdom,-21.90
303275,C563535,BANK CHARGES,Bank Charges,-1,2011-08-17 11:38:00,612.46,NaN,United Kingdom,-612.46
313427,C564494,BANK CHARGES,Bank Charges,-1,2011-08-25 14:20:00,83.83,NaN,United Kingdom,-83.83
313461,C564498,BANK CHARGES,Bank Charges,-1,2011-08-25 14:22:00,77.63,NaN,United Kingdom,-77.63
345020,C567136,BANK CHARGES,Bank Charges,-1,2011-09-16 14:27:00,366.27,NaN,United Kingdom,-366.27
388729,C570454,BANK CHARGES,Bank Charges,-1,2011-10-10 15:21:00,472.77,NaN,United Kingdom,-472.77
389027,C570463,BANK CHARGES,Bank Charges,-1,2011-10-10 15:59:00,49.65,NaN,United Kingdom,-49.65
414146,C572346,BANK CHARGES,Bank Charges,-1,2011-10-24 10:58:00,49.65,NaN,United Kingdom,-49.65
481152,C577342,BANK CHARGES,Bank Charges,-1,2011-11-18 15:11:00,490.06,NaN,United Kingdom,-490.06
481153,C577343,BANK CHARGES,Bank Charges,-1,2011-11-18 15:13:00,27.21,NaN,United Kingdom,-27.21

In [131]:
df_retail[df_retail[
    ["InvoiceNo", "StockCode"]
].duplicated()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
125,536381,71270,PHOTO CLIP LINE,3,2010-12-01 09:41:00,1.25,15311.0,United Kingdom,3.75
498,536409,90199C,5 STRAND GLASS NECKLACE CRYSTAL,1,2010-12-01 11:45:00,6.35,17908.0,United Kingdom,6.35
502,536409,85116,BLACK CANDELABRA T-LIGHT HOLDER,5,2010-12-01 11:45:00,2.10,17908.0,United Kingdom,10.50
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom,1.25
525,536409,90199C,5 STRAND GLASS NECKLACE CRYSTAL,2,2010-12-01 11:45:00,6.35,17908.0,United Kingdom,12.70
...,...,...,...,...,...,...,...,...,...
541692,581538,22992,REVOLVER WOODEN RULER,1,2011-12-09 11:34:00,1.95,14446.0,United Kingdom,1.95
541697,581538,21194,PINK HONEYCOMB PAPER FAN,1,2011-12-09 11:34:00,0.65,14446.0,United Kingdom,0.65
541698,581538,35004B,SET OF 3 BLACK FLYING DUCKS,1,2011-12-09 11:34:00,5.45,14446.0,United Kingdom,5.45
541699,581538,22694,WICKER STAR,1,2011-12-09 11:34:00,2.10,14446.0,United Kingdom,2.10
541701,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,2011-12-09 11:34:00,2.08,14446.0,United Kingdom,2.08

In [1]:
df_retail[
    ["InvoiceNo", "StockCode"]
].duplicated().sum()

NameError: name 'df_retail' is not defined

In [ ]:
df_retail[(df_retail['StockCode'] == 71270) & (df_retail['InvoiceNo'] == 536381)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
113,536381,71270,PHOTO CLIP LINE,1,2010-12-01 09:41:00,1.25,15311.0,United Kingdom,1.25
125,536381,71270,PHOTO CLIP LINE,3,2010-12-01 09:41:00,1.25,15311.0,United Kingdom,3.75

: